backbone: 'efficientnet_b2' # 'efficientnet_b0', 'resnet18', 'mobilenet_v2_140', 'efficientnet_b2', 'convnextv2_pico', 'fastvit_s12', 'densenet121', 'mixnet_l'
unfreeze_last_n: -1
dataset_dir: './datasets/cub'
batch_size: 32
num_workers: 8
optimizer: 'AdamW' # 'Adam', 'SGD', 'AdamW'
scheduler: 'CosineAnnealing' # 'CosineAnnealing', 'ReduceLROnPlateau'
epochs: 10
learning_rate: 1e-3
weight_decay: 1e-4
patience: 5
decay_factor: 0.5
loss_function: 'CrossEntropy' # 'CrossEntropy', 'FocalLoss'
label_smoothing: 0.95
gamma: 5
use_augm: False
